---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ ssh_tunnel_server_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ssh_tunnel_server_user }}"
    group: "{{ ssh_tunnel_server_user }}"

- name: Manage ssh pubkey restrictions
  ansible.builtin.template:
    src: authorized_keys.j2
    dest: "/home/{{ ssh_tunnel_server_user }}/.ssh/authorized_keys"
    mode: "0600"
    owner: "{{ ssh_tunnel_server_user }}"
    group: "{{ ssh_tunnel_server_user }}"
