---
- name: Manage service file
  ansible.builtin.template:
    src: sshtunnel.service.j2
    dest: "/etc/systemd/system/sshtunnel.service"
    mode: "0644"
    owner: root
    group: root
  notify: sshtunnel service

- name: Start and enable sshtunnel
  ansible.builtin.systemd_service:
    name: sshtunnel.service
    state: started
    enabled: true
