---
- name: Manage service file
  ansible.builtin.template:
    src: sshtunnel.service.j2
    dest: "/etc/systemd/system/sshtunnel.service"
    mode: "0644"
    owner: root
    group: root
  register: service_tmpl
  notify: sshtunnel service

- name: Start and enable sshtunnel
  ansible.builtin.systemd_service:
    name: sshtunnel.service
    state: started
    enabled: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: service_tmpl is changed
