---
- name: Create CA
  ansible.builtin.include_tasks: make_ca.yml

- name: Create DH Params
  ansible.builtin.include_tasks: make_dh.yml

- name: Create TLS-Auth Key
  ansible.builtin.include_tasks: make_ta.yml

- name: Create Server Key
  ansible.builtin.include_tasks: make_ta.yml

- name: Create Client Key(s)
  ansible.builtin.include_tasks: make_client.yml
  loop: "{{ range(1,client_count) }}"
