---
- name: Install SELinux package compilation tools
  ansible.builtin.package:
    name:
      - checkpolicy
      - policycoreutils

- name: Check for existing SELinux module
  ansible.builtin.command: |-
    semodule -l
  register: semodule_output
  changed_when: false

- name: Compile and install module if needed
  ansible.builtin.include_tasks: semodule_install.yml
  when:
    - semodule_force_reinstall or (semodule_module_name not in semodule_output.stdout_lines)
