---
- name: Check repolist
  ansible.builtin.command: |-
    dnf repolist
  register: repolist
  changed_when: false

- name: Define extra repository
  ansible.builtin.set_fact:
    extra_repo: 'ansible-automation-platform-2.5-for-rhel-{{ ansible_facts.distribution_major_version }}-{{ ansible_facts.architecture }}-rpms'

- name: Enable extra repository
  ansible.builtin.command: |-
    subscription-manager repos --enable {{ extra_repo }}

- name: Install needed packages
  ansible.builtin.package:
    name:
      - ansible-core

- name: Retrieve service facts
  ansible.builtin.service_facts:

- name: Install receptor
  when:
    - "'receptor.service' not in ansible_facts['services']"
  block:
    - name: Find instances
      ansible.builtin.uri:
        url: "https://{{ install_mesh_node_aap_hostname }}/api/controller/v2/instances"
        user: "{{ install_mesh_node_aap_username }}"
        password: "{{ install_mesh_node_aap_password }}"
        force_basic_auth: true
        validate_certs: "{{ install_mesh_node_aap_validate_certs }}"
      register: aap_instances

    - name: Retrieve local instance info
      ansible.builtin.set_fact:
        instance_info: "{{ aap_instances['json']['results'] | selectattr('hostname', 'equalto', install_mesh_node_hostname) | first }}"

    - name: Download installer bundle
      ansible.builtin.get_url:
        url: "https://{{ install_mesh_node_aap_hostname }}{{ instance_info['related']['install_bundle'] }}"
        url_username: "{{ install_mesh_node_aap_username }}"
        url_password: "{{ install_mesh_node_aap_password }}"
        force_basic_auth: true
        validate_certs: "{{ install_mesh_node_aap_validate_certs }}"
        dest: "{{ install_mesh_node_install_bundle_tarball }}"
        mode: "0644"
        owner: root
        group: root

    - name: Extract installer bundle
      ansible.builtin.unarchive:
        src: "{{ install_mesh_node_install_bundle_tarball }}"
        dest: "{{ install_mesh_node_install_bundle_dir }}"

    - name: Install requirements locally
      ansible.builtin.command:
        chdir: "{{ install_mesh_node_install_bundle_dir }}"
        cmd: |-
          ansible-galaxy collection install -r requirements.yml
      changed_when: true

    - name: Template inventory file
      ansible.builtin.template:
        src: inventory.yml.j2
        dest: "{{ install_mesh_node_install_bundle_dir }}/inventory.yml"
        mode: "0644"
        owner: root
        group: root

    - name: Run installer
      ansible.builtin.command:
        chdir: "{{ install_mesh_node_install_bundle_dir }}"
        cmd: |-
          ansible-playbook -i inventory.yml install_receptor.yml
      changed_when: true
